import type { Metadata } from 'next';
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import TopButton from "@/components/common/TopButton";
import AskButton from "@/components/common/AskButton";
import { Inter } from "next/font/google";
import { ThemeProvider } from 'next-themes';
import "@/styles/globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-screen-[1920px] mx-auto flex flex-col min-h-screen`}>
        <ThemeProvider attribute="class">
          <Header />
          <main className="flex-grow bg-custom-light-bg dark:bg-custom-dark-bg text-gray-900 dark:text-white px-4 md:px-20">
            {children}
          </main>
          <AskButton />
          <TopButton />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
