import AskButton from "@/components/common/AskButton";
import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import TopButton from "@/components/common/TopButton";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../../public/assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "FLAWDETECTOR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body
        className={`${pretendard.className} max-w-screen-[1920px] mx-auto flex min-h-screen flex-col`}
      >
        <Providers>
            <Header />
            <main className="flex flex-grow flex-col">{children}</main>
            <AskButton />
            <TopButton />
            <Footer />
        </Providers>
        <div id="modal-root" />
      </body>
    </html>
  );
}
